-- AlterTable
ALTER TABLE "Ride" ADD COLUMN     "flagReason" TEXT,
ADD COLUMN     "flagged" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "surgeMultiplier" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "trafficFactor" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "weather" TEXT NOT NULL DEFAULT 'CLEAR';
